apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: batch-job
spec:
  completions: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - date
        image: busybox
        name: batch-job
        resources: {}
      restartPolicy: Never
status: {}
