apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: updaters.dev.africodes.com
spec:
  group: dev.africodes.com
  versions:
    - name: v1
      storage: true
      served: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                age:
                  type: integer

  scope: Namespaced
  names:
    kind: UpdateTest
    singular: updater
    plural: updaters
    shortNames:
      - upd

