apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rolling-app
  name: rolling-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling-app
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rolling-app
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
status: {}
