apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: frontend-app
spec:
  containers:
          - image: mysql
            name: mysql-db
            env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: "password"
            resources:
                    requests:
                            cpu: "250m"
                            memory: "64Mi"
                    limits:
                            cpu: "500m"
                            memory: "128Mi"
          - image: wordpress
            name: wp
            resources:
                    requests:
                            cpu: "250m"
                            memory: "64Mi"
                    limits:
                            cpu: "500m"
                            memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
