apiVersion: v1
kind: Pod
metadata:
        name: init-container
spec:
        containers:
                - name: webserver
                  image: nginx
        initContainers:
                - name: initial
                  image: busybox
                  command: ["sleep", "300"]
