apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxweb
  name: nginxweb
spec:
  containers:
  - image: nginx
    name: nginxweb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
