apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-sa
  name: nginx-sa
spec:
  containers:
  - image: nginx
    name: nginx-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: dashboard-acc 
status: {}
