apiVersion: v1
kind: Pod
metadata: 
  name: busybox-context-1
spec:
        containers:
                - image: busybox
                  name: busybox-context
                  command: [ "sh", "-c", "sleep 1h" ]
                  volumeMounts:
                          - name: localstore
                            mountPath: /data/demo
                  securityContext:
                          allowPrivilegeEscalation: false
        volumes:
                - name: localstore
                  emptyDir: {}
        securityContext:
                runAsUser: 1001
                runAsGroup: 2001
                fsGroup: 3001
