apiVersion: v1
kind: Pod
metadata:
        name: sidecar-nginx
        labels:
                tier: sidecar-web
spec:
        volumes:
                - name: webdir
                  emptyDir: {}
        containers:
                - name: sidecar-app
                  image: nginx
                  ports:
                          - name: web-port
                            containerPort: 80
                  volumeMounts:
                          - name: webdir
                            mountPath: /usr/share/nginx/html

                - name: main-app
                  image: busybox
                  volumeMounts:
                          - name: webdir
                            mountPath: /html
                  command:
                          - "/bin/sh"
                          - "-c"
                  args: ["while true; do date >> /html/index.html;sleep 100;done"]
