apiVersion: v1
kind: Pod
metadata:
        name: busybox-naked-pod1
        namespace: default
spec:
        containers:
                -
                  name: busyboxpod
                  image: busybox
                  command:
                          - sleep
                          - "3600"
                - name: nginx-pod
                  image: nginx
