apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend-resource-limits
  name: frontend-resource-limits
spec:
  containers:
          - image: nginx
            name: frontend-resource-limits
            resources:
                    requests:
                            cpu: "1"
                            memory: "128Mi"
                    limits:
                            cpu: "2"
                            memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
