apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express-app
  name: mongo-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-express-app
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "admin"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "password"
          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongo"
        ports:
        - containerPort: 8081
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express-app
  name: mongo-express-app
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongo-express-app
status:
  loadBalancer: {}
