apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mybbox
  name: mybbox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: mybbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
