apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: initcontainer3
  name: initcontainer3
spec:
  containers:
  - image: nginx
    name: initcontainer3
    resources: {}
  initContainers:
  - image: alpine
    name: init-gitclone
    command: ["/bin/sh", "-c"]
    args: ["apk add git", "sleep 60","git clone https://github.com/stynhaq/empty-repo.git"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
